name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: generate pacman
        uses: gluons/pacman-contribution-graph@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          outputDir: dist

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}